"""Source: https://thoughtcatalog.com/juliet-lanka/2018/03/70-roasting-jokes-to-burn-your-frenemies-when-the-middle-finger-wont-cut-it/
https://www.geckoandfly.com/21355/funny-non-swearing-insults-sarcastic-quotes/
"""

roast_quotes = [
    "My phone battery lasts longer than your relationships.",
    "Oh you’re talking to me, I thought you only talked behind my back.",
    "My name must taste good because it’s always in your mouth. ",
    "Too bad you can’t count jumping to conclusions and running your mouth as exercise.",
    "Is your drama going to an intermission soon?",
    "It’s a shame you can’t Photoshop your personality.",
    "Acting like a prick doesn’t make yours grow bigger.",
    "Jealousy is a disease. Get well soon, bitch! ",
    "When karma comes back to punch you in the face, I want to be there in case it needs help.",
    "You have more faces than Mount Rushmore.",
    "Don’t mistake my silence for weakness. No one plans a murder out loud. ",
    "I’m sorry you got offended that one time you were treated the way you treat everyone all the time. ",
    "You should wear a condom on your head. If you’re going to be a dick, you might as well dress like one. ",
    "Being a bitch is a tough job but someone has to do it. ",
    "I’m sorry that my brutal honesty inconvenienced your ego.",
    "Is there an app I can download to make you disappear?",
    "I’m visualizing duck tape over your mouth.",
    "My hair straightener is hotter than you.",
    "I’d smack you, but that would be animal abuse.",
    "It’s scary to think people like you are allowed to vote. ",
    "Keep rolling your eyes. Maybe you’ll find your brain back there.",
    "No, no. I am listening. It just takes me a moment to process so much stupid information all at once.",
    "You’re the reason I prefer animals to people. ",
    "I’d explain it to you but I left my English-to-Dumbass Dictionary at home.",
    "I’m sorry I hurt your feelings when I called you stupid. I really thought you already knew.",
    "I’m not insulting you. I’m describing you.",
    "Some people just need a high five. In the face. With a chair.",
    "If you don’t like me, take a map, get a car, drive to hell. Have a nice trip.",
    "If I wanted to kill myself I would climb your ego and jump to your IQ.",
    ""
]

simaris_quotes = [
    "Ah... I see we are of like mind. The Sanctuary will be your project too.",
    "Hunter, my research needs you. Are you ready to endure the rigors of the Sanctuary?",
    "Go then. Some other Hunter will have mettle enough to assist me.",
    "Show me your dedication to the Sanctuary.",
    "I can see you're hungry for the knowledge of the Sanctuary.",
    "You are a true hunter. Where would the Sanctuary be without you?",
    "Ah... I see you are of like mind. The Sanctuary will be your project too.",
    "The multitude of creatures you have immortalized would cry out in thanks... If they could.",
    "The Sanctuary must grow. It must preserve. It must endure. Hunt this being for me, and I will enlighten you.",
    "I have selected a new specimen for Sanctuary. It is time for you and your kind to hunt again. Knowledge will be your reward.",
    "Cast off your ignorant veil, Tenno! Collect your arms, your allies, and hunt this creature for me. I will reward you, should you perform Synthesis.",
    "Knowledge must be earned, Tenno. I will share what I know, but you must prove yourself deserving. Hunt this creature for me, perform Synthesis, and you will be enlightened.",
    "I must determine a new target. This task cannot be rushed. Leave me.",
    "Time is required to analyze your previous contribution. I will have a new target for you in the near future.",
    "I can see you are hungry for knowledge, but that hunger must be matched by patience. Return later to see if a new target has been selected.",
    "This specimen is shrouded in mystery. Will you enlighten us with its imprint?",
    "Synthesis will be the light that illuminates this creature. With your help, of course.",
    "This fine specimen could be the next addition to the Sanctuary. Help me discover its secrets.",
    "Hunter, this target is my current obsession. I must know its every detail. Will you oblige my passion?",
    "I have a thirst for knowledge that only Synthesis can satisfy. This being is current object of my curiosity.",
    "Good fortune, Hunter.",
    "I knew we had a shared passion, Hunter.",
    "The Sanctuary and I await your contribution.",
    "Good. Even while others are blinded by petty morality, you recognized the virtue of the Sanctuary.",
    "Not to worry. There are other Hunters more suited to this task.",
    "This Sanctuary will go on without you, but can you go on without the Sanctuary?",
    "It seems you have lost the fortitude the Sanctuary requires of its Hunters. A shame.",
    "Unfortunate. You should know that I now regret seeking your assistance.",
    "You must have reasons for abandoning the Sanctuary. Ask yourself, are they valid?",
    "What a pity this creature will forever be unaware of its contribution to the Sanctuary",
    "You are a trustworthy hunter. Come back later and I will have a new target for you.",
    "I can tell, you find thrill in the hunt. Come back later for a new target.",
    "Do you ever wonder why only the Hunter is rewarded when it is the specimen that gives all to the Sanctuary? I find it best to discard such thoughts.",
    "I can see you are hungry for the knowledge of the Sanctuary.",
    "Tenno, you will make an excellent hunter.",
    "You may explore the Sanctuary for new knowledge.",
    "Hunter, my research needs you. Are you ready to endure the rigors of the Sanctuary?",
    "Your thirst for knowledge is as insatiable as mine.",
    "Your duty in this experiment is to dispatch as many specimens as efficiently as possible. When the time comes, I will open the next data-conduit.",
    "This is a stress test. Destroy all specimens as quickly as possible. In this chaos, the true nature of these creatures will be revealed… as will yours.",
    "Hunter, you are running out of time. Enter the data-conduit.",
    "Do not weep for these creatures… they are immortal, they can and have faced a billion deaths. You, however, do not enjoy the protections of synthesis. For you, failure has real-life consequences.",
    "Feel it now? That stress. You’re generating useful data, Hunter.",
]
