name: Bot Deployment
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    # Job name is Greeting
    name: Bot deployment
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: build_time
      # This step prints an output (time) from the previous step's action.
      - name: Echo the deployment time
        run: echo 'The time was ${{ steps.build_time.outputs.time }}.'